// Auto-generated by scripts/fetch-products.mjs. Do not edit by hand.

export type StaticAppearance = {
  id: string
  name: string
  color: string
  image: string
}

export type StaticProduct = {
  id: string
  name: string
  price: number
  preview: string
  appearances: StaticAppearance[]
  sizes: string[]
}

export const FEATURED_PRODUCT_ID = "2940"

export const PRODUCTS: StaticProduct[] = [
  {
    "id": "2940",
    "name": "Unisex Premium Oversized Organic T-Shirt",
    "price": 19.74,
    "preview": "/products/2940/1251.webp",
    "appearances": [
      {
        "id": "1251",
        "name": "mauve",
        "color": "#BA7283",
        "image": "/products/2940/1251.webp"
      },
      {
        "id": "1256",
        "name": "heather anthracite",
        "color": "#2F3031",
        "image": "/products/2940/1256.webp"
      },
      {
        "id": "1257",
        "name": "black",
        "color": "#1A1A1A",
        "image": "/products/2940/1257.webp"
      },
      {
        "id": "1258",
        "name": "white",
        "color": "#F4F5F0",
        "image": "/products/2940/1258.webp"
      },
      {
        "id": "1261",
        "name": "beige",
        "color": "#CDC6BD",
        "image": "/products/2940/1261.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/2940/1269.webp"
      },
      {
        "id": "1274",
        "name": "khaki",
        "color": "#5B5F38",
        "image": "/products/2940/1274.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "id": "6",
    "name": "Men's T-shirt",
    "price": 16.24,
    "preview": "/products/6/403.webp",
    "appearances": [
      {
        "id": "403",
        "name": "sage",
        "color": "#C1D5AA",
        "image": "/products/6/403.webp"
      },
      {
        "id": "648",
        "name": "charcoal grey",
        "color": "#605E5E",
        "image": "/products/6/648.webp"
      },
      {
        "id": "715",
        "name": "military green",
        "color": "#6E7C54",
        "image": "/products/6/715.webp"
      },
      {
        "id": "729",
        "name": "graphite heather",
        "color": "#716969",
        "image": "/products/6/729.webp"
      },
      {
        "id": "868",
        "name": "brick red",
        "color": "#921F2F",
        "image": "/products/6/868.webp"
      },
      {
        "id": "950",
        "name": "majorelle blue",
        "color": "#254E98",
        "image": "/products/6/950.webp"
      },
      {
        "id": "1175",
        "name": "carolina blue",
        "color": "#86A1CD",
        "image": "/products/6/1175.webp"
      },
      {
        "id": "1704",
        "name": "dark denim",
        "color": "#465777",
        "image": "/products/6/1704.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/6/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/6/2.webp"
      },
      {
        "id": "5",
        "name": "red",
        "color": "#F51E30",
        "image": "/products/6/5.webp"
      },
      {
        "id": "4",
        "name": "navy",
        "color": "#00224C",
        "image": "/products/6/4.webp"
      },
      {
        "id": "92",
        "name": "kelly green",
        "color": "#1E9658",
        "image": "/products/6/92.webp"
      },
      {
        "id": "231",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/6/231.webp"
      },
      {
        "id": "444",
        "name": "purple",
        "color": "#6B3F7F",
        "image": "/products/6/444.webp"
      },
      {
        "id": "7",
        "name": "yellow",
        "color": "#F7EF00",
        "image": "/products/6/7.webp"
      },
      {
        "id": "526",
        "name": "pink",
        "color": "#FE8FB6",
        "image": "/products/6/526.webp"
      },
      {
        "id": "337",
        "name": "sand beige",
        "color": "#BBB29D",
        "image": "/products/6/337.webp"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL"
    ]
  },
  {
    "id": "631",
    "name": "Women's T-Shirt",
    "price": 16.24,
    "preview": "/products/631/1458.webp",
    "appearances": [
      {
        "id": "1458",
        "name": "antique blue sapphire heather",
        "color": "#1B6FA8",
        "image": "/products/631/1458.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/631/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/631/2.webp"
      },
      {
        "id": "5",
        "name": "red",
        "color": "#F51E30",
        "image": "/products/631/5.webp"
      },
      {
        "id": "4",
        "name": "navy",
        "color": "#00224C",
        "image": "/products/631/4.webp"
      },
      {
        "id": "92",
        "name": "kelly green",
        "color": "#1E9658",
        "image": "/products/631/92.webp"
      },
      {
        "id": "231",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/631/231.webp"
      },
      {
        "id": "258",
        "name": "royal blue",
        "color": "#48599B",
        "image": "/products/631/258.webp"
      },
      {
        "id": "194",
        "name": "azalea",
        "color": "#F24173",
        "image": "/products/631/194.webp"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": "724",
    "name": "Kids' T-Shirt",
    "price": 15.99,
    "preview": "/products/724/813.webp",
    "appearances": [
      {
        "id": "813",
        "name": "dark grey",
        "color": "#3B3B3B",
        "image": "/products/724/813.webp"
      },
      {
        "id": "1195",
        "name": "sky blue",
        "color": "#8EB8F2",
        "image": "/products/724/1195.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/724/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/724/2.webp"
      },
      {
        "id": "5",
        "name": "red",
        "color": "#F51E30",
        "image": "/products/724/5.webp"
      },
      {
        "id": "92",
        "name": "kelly green",
        "color": "#1E9658",
        "image": "/products/724/92.webp"
      },
      {
        "id": "438",
        "name": "forest green",
        "color": "#1B471E",
        "image": "/products/724/438.webp"
      },
      {
        "id": "17",
        "name": "royal blue",
        "color": "#3450B5",
        "image": "/products/724/17.webp"
      },
      {
        "id": "231",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/724/231.webp"
      },
      {
        "id": "316",
        "name": "gold",
        "color": "#F5AC0C",
        "image": "/products/724/316.webp"
      },
      {
        "id": "399",
        "name": "navy",
        "color": "#212735",
        "image": "/products/724/399.webp"
      },
      {
        "id": "29",
        "name": "orange",
        "color": "#FA6807",
        "image": "/products/724/29.webp"
      }
    ],
    "sizes": [
      "98/104 (3-4 Years)",
      "110/116 (5-6 Years)",
      "122/128 (7-8 Years)"
    ]
  },
  {
    "id": "1047",
    "name": "Unisex Hoodie",
    "price": 30.49,
    "preview": "/products/1047/424.webp",
    "appearances": [
      {
        "id": "424",
        "name": "pink",
        "color": "#E96F98",
        "image": "/products/1047/424.webp"
      },
      {
        "id": "577",
        "name": "light heather grey",
        "color": "#CBCBCB",
        "image": "/products/1047/577.webp"
      },
      {
        "id": "648",
        "name": "charcoal grey",
        "color": "#605E5E",
        "image": "/products/1047/648.webp"
      },
      {
        "id": "649",
        "name": "steel green",
        "color": "#A7B6AC",
        "image": "/products/1047/649.webp"
      },
      {
        "id": "764",
        "name": "vanilla",
        "color": "#EFE9D6",
        "image": "/products/1047/764.webp"
      },
      {
        "id": "765",
        "name": "peach",
        "color": "#E2BC94",
        "image": "/products/1047/765.webp"
      },
      {
        "id": "766",
        "name": "mocha",
        "color": "#947564",
        "image": "/products/1047/766.webp"
      },
      {
        "id": "795",
        "name": "stonewash blue",
        "color": "#8DA5B1",
        "image": "/products/1047/795.webp"
      },
      {
        "id": "874",
        "name": "bright royal",
        "color": "#25318B",
        "image": "/products/1047/874.webp"
      },
      {
        "id": "924",
        "name": "elephant grey",
        "color": "#858585",
        "image": "/products/1047/924.webp"
      },
      {
        "id": "1253",
        "name": "bottle green",
        "color": "#29573C",
        "image": "/products/1047/1253.webp"
      },
      {
        "id": "1318",
        "name": "pastel turquoise",
        "color": "#79B3AF",
        "image": "/products/1047/1318.webp"
      },
      {
        "id": "1461",
        "name": "deep sea blue ",
        "color": "#006185",
        "image": "/products/1047/1461.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/1047/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/1047/2.webp"
      },
      {
        "id": "196",
        "name": "red",
        "color": "#D41C28",
        "image": "/products/1047/196.webp"
      },
      {
        "id": "92",
        "name": "kelly green",
        "color": "#1E9658",
        "image": "/products/1047/92.webp"
      },
      {
        "id": "22",
        "name": "bordeaux",
        "color": "#750033",
        "image": "/products/1047/22.webp"
      },
      {
        "id": "399",
        "name": "navy",
        "color": "#212735",
        "image": "/products/1047/399.webp"
      },
      {
        "id": "152",
        "name": "mint",
        "color": "#76D1BD",
        "image": "/products/1047/152.webp"
      },
      {
        "id": "141",
        "name": "lavender",
        "color": "#B3A0C9",
        "image": "/products/1047/141.webp"
      },
      {
        "id": "29",
        "name": "orange",
        "color": "#FA6807",
        "image": "/products/1047/29.webp"
      },
      {
        "id": "32",
        "name": "beige",
        "color": "#CBB48E",
        "image": "/products/1047/32.webp"
      },
      {
        "id": "301",
        "name": "lemon yellow",
        "color": "#F6E579",
        "image": "/products/1047/301.webp"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL"
    ]
  },
  {
    "id": "20",
    "name": "Men’s Premium Organic Hoodie",
    "price": 37.74,
    "preview": "/products/20/1247.webp",
    "appearances": [
      {
        "id": "1247",
        "name": "taupe",
        "color": "#B1A5A0",
        "image": "/products/20/1247.webp"
      },
      {
        "id": "1250",
        "name": "dusky pink",
        "color": "#D4B9C5",
        "image": "/products/20/1250.webp"
      },
      {
        "id": "1253",
        "name": "bottle green",
        "color": "#29573C",
        "image": "/products/20/1253.webp"
      },
      {
        "id": "1254",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/20/1254.webp"
      },
      {
        "id": "1256",
        "name": "heather anthracite",
        "color": "#2F3031",
        "image": "/products/20/1256.webp"
      },
      {
        "id": "1259",
        "name": "off white",
        "color": "#ECE7E0",
        "image": "/products/20/1259.webp"
      },
      {
        "id": "1261",
        "name": "beige",
        "color": "#CDC6BD",
        "image": "/products/20/1261.webp"
      },
      {
        "id": "1264",
        "name": "burgundy",
        "color": "#6A2A39",
        "image": "/products/20/1264.webp"
      },
      {
        "id": "1265",
        "name": "red",
        "color": "#BB1E1E",
        "image": "/products/20/1265.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/20/1269.webp"
      },
      {
        "id": "1271",
        "name": "stone blue",
        "color": "#5A7199",
        "image": "/products/20/1271.webp"
      },
      {
        "id": "1274",
        "name": "khaki",
        "color": "#5B5F38",
        "image": "/products/20/1274.webp"
      },
      {
        "id": "1278",
        "name": "royal blue",
        "color": "#1F2E7F",
        "image": "/products/20/1278.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/20/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/20/2.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL",
      "5XL"
    ]
  },
  {
    "id": "1505",
    "name": "Kids Hoodie",
    "price": 26.49,
    "preview": "/products/1505/394.webp",
    "appearances": [
      {
        "id": "394",
        "name": "yellow",
        "color": "#FCE940",
        "image": "/products/1505/394.webp"
      },
      {
        "id": "424",
        "name": "pink",
        "color": "#E96F98",
        "image": "/products/1505/424.webp"
      },
      {
        "id": "577",
        "name": "light heather grey",
        "color": "#CBCBCB",
        "image": "/products/1505/577.webp"
      },
      {
        "id": "649",
        "name": "steel green",
        "color": "#A7B6AC",
        "image": "/products/1505/649.webp"
      },
      {
        "id": "763",
        "name": "dusky rose",
        "color": "#D5958C",
        "image": "/products/1505/763.webp"
      },
      {
        "id": "874",
        "name": "bright royal",
        "color": "#25318B",
        "image": "/products/1505/874.webp"
      },
      {
        "id": "1037",
        "name": "sand",
        "color": "#DFCAB7",
        "image": "/products/1505/1037.webp"
      },
      {
        "id": "1253",
        "name": "bottle green",
        "color": "#29573C",
        "image": "/products/1505/1253.webp"
      },
      {
        "id": "1584",
        "name": "peppermint",
        "color": "#97EDEB",
        "image": "/products/1505/1584.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/1505/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/1505/2.webp"
      },
      {
        "id": "196",
        "name": "red",
        "color": "#D41C28",
        "image": "/products/1505/196.webp"
      },
      {
        "id": "92",
        "name": "kelly green",
        "color": "#1E9658",
        "image": "/products/1505/92.webp"
      },
      {
        "id": "22",
        "name": "bordeaux",
        "color": "#750033",
        "image": "/products/1505/22.webp"
      },
      {
        "id": "399",
        "name": "navy",
        "color": "#212735",
        "image": "/products/1505/399.webp"
      },
      {
        "id": "141",
        "name": "lavender",
        "color": "#B3A0C9",
        "image": "/products/1505/141.webp"
      },
      {
        "id": "29",
        "name": "orange",
        "color": "#FA6807",
        "image": "/products/1505/29.webp"
      },
      {
        "id": "326",
        "name": "sea blue",
        "color": "#0083BD",
        "image": "/products/1505/326.webp"
      }
    ],
    "sizes": [
      "XS (3/4 years)",
      "S (5/6 Years)",
      "M (7/8 Years)"
    ]
  },
  {
    "id": "3980",
    "name": "Striped tennis socks",
    "price": 12.49,
    "preview": "/products/3980/586.webp",
    "appearances": [
      {
        "id": "586",
        "name": "white/yellow",
        "color": "#FFFFFF",
        "image": "/products/3980/586.webp"
      },
      {
        "id": "587",
        "name": "white/blue",
        "color": "#FFFFFF",
        "image": "/products/3980/587.webp"
      },
      {
        "id": "1529",
        "name": "white/lilac ",
        "color": "#FFFFFF",
        "image": "/products/3980/1529.webp"
      },
      {
        "id": "1530",
        "name": "white/mint",
        "color": "#FFFFFF",
        "image": "/products/3980/1530.webp"
      },
      {
        "id": "1531",
        "name": "white/peach",
        "color": "#FFFFFF",
        "image": "/products/3980/1531.webp"
      },
      {
        "id": "70",
        "name": "white/black",
        "color": "#FFFFFF",
        "image": "/products/3980/70.webp"
      },
      {
        "id": "26",
        "name": "white/navy",
        "color": "#FFFFFF",
        "image": "/products/3980/26.webp"
      },
      {
        "id": "71",
        "name": "white/red",
        "color": "#FFFFFF",
        "image": "/products/3980/71.webp"
      },
      {
        "id": "80",
        "name": "white/green",
        "color": "#FFFFFF",
        "image": "/products/3980/80.webp"
      }
    ],
    "sizes": [
      "37-41",
      "42-46"
    ]
  },
  {
    "id": "3001",
    "name": "Tennis socks",
    "price": 13.49,
    "preview": "/products/3001/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/3001/1.webp"
      }
    ],
    "sizes": [
      "37-41",
      "42-46"
    ]
  },
  {
    "id": "4312",
    "name": "Kids Tennis Socks",
    "price": 10.49,
    "preview": "/products/4312/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/4312/1.webp"
      }
    ],
    "sizes": [
      "27 - 31",
      "32 - 36"
    ]
  },
  {
    "id": "56",
    "name": "Tote Bag",
    "price": 12.74,
    "preview": "/products/56/404.webp",
    "appearances": [
      {
        "id": "404",
        "name": "nature",
        "color": "#E1DABC",
        "image": "/products/56/404.webp"
      },
      {
        "id": "494",
        "name": "light blue",
        "color": "#4E6DB3",
        "image": "/products/56/494.webp"
      },
      {
        "id": "741",
        "name": "burgundy",
        "color": "#761F32",
        "image": "/products/56/741.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/56/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/56/2.webp"
      },
      {
        "id": "5",
        "name": "red",
        "color": "#F51E30",
        "image": "/products/56/5.webp"
      },
      {
        "id": "17",
        "name": "royal blue",
        "color": "#3450B5",
        "image": "/products/56/17.webp"
      },
      {
        "id": "307",
        "name": "graphite grey",
        "color": "#525453",
        "image": "/products/56/307.webp"
      },
      {
        "id": "194",
        "name": "azalea",
        "color": "#F24173",
        "image": "/products/56/194.webp"
      },
      {
        "id": "360",
        "name": "evergreen",
        "color": "#2F683D",
        "image": "/products/56/360.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "4133",
    "name": "Midweight Recycled Tote Bag by Stanley/Stella",
    "price": 15.49,
    "preview": "/products/4133/718.webp",
    "appearances": [
      {
        "id": "718",
        "name": "bottle green",
        "color": "#385F44",
        "image": "/products/4133/718.webp"
      },
      {
        "id": "741",
        "name": "burgundy",
        "color": "#761F32",
        "image": "/products/4133/741.webp"
      },
      {
        "id": "742",
        "name": "anthracite",
        "color": "#5F5F5F",
        "image": "/products/4133/742.webp"
      },
      {
        "id": "938",
        "name": "navy",
        "color": "#1F2B3A",
        "image": "/products/4133/938.webp"
      },
      {
        "id": "1189",
        "name": "stargazer",
        "color": "#48646B",
        "image": "/products/4133/1189.webp"
      },
      {
        "id": "1409",
        "name": "heritage brown",
        "color": "#AC5442",
        "image": "/products/4133/1409.webp"
      },
      {
        "id": "1410",
        "name": "desert dust",
        "color": "#CFC2B1",
        "image": "/products/4133/1410.webp"
      },
      {
        "id": "1474",
        "name": "mindful blue",
        "color": "#276CA1",
        "image": "/products/4133/1474.webp"
      },
      {
        "id": "1524",
        "name": "purple love ",
        "color": "#55439A",
        "image": "/products/4133/1524.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/4133/2.webp"
      },
      {
        "id": "968",
        "name": "pink",
        "color": "#F092B3",
        "image": "/products/4133/968.webp"
      },
      {
        "id": "239",
        "name": "sky",
        "color": "#BACAE0",
        "image": "/products/4133/239.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "2973",
    "name": "Stanley/Stella Organic Tote Bag",
    "price": 15.49,
    "preview": "/products/2973/741.webp",
    "appearances": [
      {
        "id": "741",
        "name": "burgundy",
        "color": "#761F32",
        "image": "/products/2973/741.webp"
      },
      {
        "id": "742",
        "name": "anthracite",
        "color": "#5F5F5F",
        "image": "/products/2973/742.webp"
      },
      {
        "id": "947",
        "name": "soft Ecru",
        "color": "#EFE9D7",
        "image": "/products/2973/947.webp"
      },
      {
        "id": "990",
        "name": "bright orange",
        "color": "#EA5C03",
        "image": "/products/2973/990.webp"
      },
      {
        "id": "1188",
        "name": "khaki",
        "color": "#635840",
        "image": "/products/2973/1188.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/2973/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/2973/2.webp"
      },
      {
        "id": "196",
        "name": "red",
        "color": "#D41C28",
        "image": "/products/2973/196.webp"
      },
      {
        "id": "338",
        "name": "royal blue",
        "color": "#4164A1",
        "image": "/products/2973/338.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "1040",
    "name": "Trucker Cap",
    "price": 17.49,
    "preview": "/products/1040/942.webp",
    "appearances": [
      {
        "id": "942",
        "name": "pale pink",
        "color": "#FBDDD9",
        "image": "/products/1040/942.webp"
      },
      {
        "id": "1320",
        "name": "black/stone grey",
        "color": "#000000",
        "image": "/products/1040/1320.webp"
      },
      {
        "id": "1321",
        "name": "brown/beige",
        "color": "#5B4642",
        "image": "/products/1040/1321.webp"
      },
      {
        "id": "70",
        "name": "white/black",
        "color": "#FFFFFF",
        "image": "/products/1040/70.webp"
      },
      {
        "id": "26",
        "name": "white/navy",
        "color": "#FFFFFF",
        "image": "/products/1040/26.webp"
      },
      {
        "id": "71",
        "name": "white/red",
        "color": "#FFFFFF",
        "image": "/products/1040/71.webp"
      },
      {
        "id": "14",
        "name": "black/black",
        "color": "#000000",
        "image": "/products/1040/14.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "4562",
    "name": "Kids’ Trucker Cap",
    "price": 10.49,
    "preview": "/products/4562/820.webp",
    "appearances": [
      {
        "id": "820",
        "name": "light grey",
        "color": "#B4B2AD",
        "image": "/products/4562/820.webp"
      },
      {
        "id": "942",
        "name": "pale pink",
        "color": "#FBDDD9",
        "image": "/products/4562/942.webp"
      },
      {
        "id": "1280",
        "name": "olive/black",
        "color": "#6F6D59",
        "image": "/products/4562/1280.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/4562/1.webp"
      },
      {
        "id": "26",
        "name": "white/navy",
        "color": "#FFFFFF",
        "image": "/products/4562/26.webp"
      },
      {
        "id": "71",
        "name": "white/red",
        "color": "#FFFFFF",
        "image": "/products/4562/71.webp"
      },
      {
        "id": "14",
        "name": "black/black",
        "color": "#000000",
        "image": "/products/4562/14.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "15",
    "name": "Baseball Cap",
    "price": 20.74,
    "preview": "/products/15/1253.webp",
    "appearances": [
      {
        "id": "1253",
        "name": "bottle green",
        "color": "#29573C",
        "image": "/products/15/1253.webp"
      },
      {
        "id": "10",
        "name": "white/white",
        "color": "#FFFFFF",
        "image": "/products/15/10.webp"
      },
      {
        "id": "14",
        "name": "black/black",
        "color": "#000000",
        "image": "/products/15/14.webp"
      },
      {
        "id": "261",
        "name": "classic red",
        "color": "#C60812",
        "image": "/products/15/261.webp"
      },
      {
        "id": "13",
        "name": "blue/blue",
        "color": "#222244",
        "image": "/products/15/13.webp"
      },
      {
        "id": "272",
        "name": "grey",
        "color": "#E1E1E5",
        "image": "/products/15/272.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "31",
    "name": "Mug",
    "price": 10.74,
    "preview": "/products/31/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/31/1.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "1313",
    "name": "Camper Mug",
    "price": 12.49,
    "preview": "/products/1313/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/1313/1.webp"
      },
      {
        "id": "71",
        "name": "white/red",
        "color": "#FFFFFF",
        "image": "/products/1313/71.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "1470",
    "name": "Large Mug 440 ml",
    "price": 12.49,
    "preview": "/products/1470/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/1470/1.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "4506",
    "name": "Sticker size XS (5 x 5 cm)",
    "price": 1.49,
    "preview": "/products/4506/839.webp",
    "appearances": [
      {
        "id": "839",
        "name": "white matte",
        "color": "#FFFFFF",
        "image": "/products/4506/839.webp"
      },
      {
        "id": "840",
        "name": "white glossy",
        "color": "#FFFFFF",
        "image": "/products/4506/840.webp"
      },
      {
        "id": "842",
        "name": "transparent glossy",
        "color": "#FFFFFF",
        "image": "/products/4506/842.webp"
      }
    ],
    "sizes": [
      "5 x 5 cm"
    ]
  },
  {
    "id": "1459",
    "name": "Sticker size S (10 x 10 cm)",
    "price": 2.49,
    "preview": "/products/1459/839.webp",
    "appearances": [
      {
        "id": "839",
        "name": "white matte",
        "color": "#FFFFFF",
        "image": "/products/1459/839.webp"
      },
      {
        "id": "840",
        "name": "white glossy",
        "color": "#FFFFFF",
        "image": "/products/1459/840.webp"
      },
      {
        "id": "842",
        "name": "transparent glossy",
        "color": "#FFFFFF",
        "image": "/products/1459/842.webp"
      }
    ],
    "sizes": [
      "10 x 10 cm"
    ]
  },
  {
    "id": "4505",
    "name": "Sticker size M (15 x 15 cm)",
    "price": 5.99,
    "preview": "/products/4505/839.webp",
    "appearances": [
      {
        "id": "839",
        "name": "white matte",
        "color": "#FFFFFF",
        "image": "/products/4505/839.webp"
      },
      {
        "id": "840",
        "name": "white glossy",
        "color": "#FFFFFF",
        "image": "/products/4505/840.webp"
      },
      {
        "id": "842",
        "name": "transparent glossy",
        "color": "#FFFFFF",
        "image": "/products/4505/842.webp"
      }
    ],
    "sizes": [
      "15 x 15 cm"
    ]
  },
  {
    "id": "943",
    "name": "Women’s Premium Organic Top",
    "price": 21.74,
    "preview": "/products/943/1250.webp",
    "appearances": [
      {
        "id": "1250",
        "name": "dusky pink",
        "color": "#D4B9C5",
        "image": "/products/943/1250.webp"
      },
      {
        "id": "1252",
        "name": "mint ",
        "color": "#AED9CF",
        "image": "/products/943/1252.webp"
      },
      {
        "id": "1254",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/943/1254.webp"
      },
      {
        "id": "1264",
        "name": "burgundy",
        "color": "#6A2A39",
        "image": "/products/943/1264.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/943/1269.webp"
      },
      {
        "id": "1271",
        "name": "stone blue",
        "color": "#5A7199",
        "image": "/products/943/1271.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/943/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/943/2.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "id": "916",
    "name": "Men's Premium Organic Tank Top",
    "price": 16.99,
    "preview": "/products/916/648.webp",
    "appearances": [
      {
        "id": "648",
        "name": "charcoal grey",
        "color": "#605E5E",
        "image": "/products/916/648.webp"
      },
      {
        "id": "1256",
        "name": "heather anthracite",
        "color": "#2F3031",
        "image": "/products/916/1256.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/916/1269.webp"
      },
      {
        "id": "1274",
        "name": "khaki",
        "color": "#5B5F38",
        "image": "/products/916/1274.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/916/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/916/2.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL",
      "5XL"
    ]
  },
  {
    "id": "917",
    "name": "Women’s Premium Organic Tank top",
    "price": 16.99,
    "preview": "/products/917/1251.webp",
    "appearances": [
      {
        "id": "1251",
        "name": "mauve",
        "color": "#BA7283",
        "image": "/products/917/1251.webp"
      },
      {
        "id": "1254",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/917/1254.webp"
      },
      {
        "id": "1256",
        "name": "heather anthracite",
        "color": "#2F3031",
        "image": "/products/917/1256.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/917/1269.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/917/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/917/2.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "id": "1434",
    "name": "Kids Premium Organic Sweatshirt",
    "price": 33.99,
    "preview": "/products/1434/1249.webp",
    "appearances": [
      {
        "id": "1249",
        "name": "rose",
        "color": "#FFCDCF",
        "image": "/products/1434/1249.webp"
      },
      {
        "id": "1265",
        "name": "red",
        "color": "#BB1E1E",
        "image": "/products/1434/1265.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/1434/1269.webp"
      },
      {
        "id": "1278",
        "name": "royal blue",
        "color": "#1F2E7F",
        "image": "/products/1434/1278.webp"
      },
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/1434/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/1434/2.webp"
      }
    ],
    "sizes": [
      "98/104 (2 Years)",
      "110/116 (4 Years)",
      "122/128 (6 Years)",
      "134/140 (8 Years)",
      "146/152 (10 Years)",
      "158/164 (12 Years)"
    ]
  },
  {
    "id": "4504",
    "name": "Unisex Organic Zip Sweatshirt by Stanley/Stella",
    "price": 50.49,
    "preview": "/products/4504/718.webp",
    "appearances": [
      {
        "id": "718",
        "name": "bottle green",
        "color": "#385F44",
        "image": "/products/4504/718.webp"
      },
      {
        "id": "741",
        "name": "burgundy",
        "color": "#761F32",
        "image": "/products/4504/741.webp"
      },
      {
        "id": "938",
        "name": "navy",
        "color": "#1F2B3A",
        "image": "/products/4504/938.webp"
      },
      {
        "id": "1410",
        "name": "desert dust",
        "color": "#CFC2B1",
        "image": "/products/4504/1410.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/4504/2.webp"
      },
      {
        "id": "231",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/4504/231.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "id": "2962",
    "name": "Women’s Premium Organic Sweatshorts",
    "price": 21.99,
    "preview": "/products/2962/1254.webp",
    "appearances": [
      {
        "id": "1254",
        "name": "heather grey",
        "color": "#BEBEBE",
        "image": "/products/2962/1254.webp"
      },
      {
        "id": "1257",
        "name": "black",
        "color": "#1A1A1A",
        "image": "/products/2962/1257.webp"
      },
      {
        "id": "1269",
        "name": "navy",
        "color": "#2E303B",
        "image": "/products/2962/1269.webp"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "id": "3928",
    "name": "Framed poster (27 × 37 cm)",
    "price": 17.49,
    "preview": "/products/3928/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/3928/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/3928/2.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "3929",
    "name": "Framed poster (37 × 27 cm)",
    "price": 17.49,
    "preview": "/products/3929/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/3929/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/3929/2.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  },
  {
    "id": "3930",
    "name": "Framed poster (49 × 69 cm)",
    "price": 27.49,
    "preview": "/products/3930/1.webp",
    "appearances": [
      {
        "id": "1",
        "name": "white",
        "color": "#FFFFFF",
        "image": "/products/3930/1.webp"
      },
      {
        "id": "2",
        "name": "black",
        "color": "#000000",
        "image": "/products/3930/2.webp"
      }
    ],
    "sizes": [
      "One Size"
    ]
  }
]
